import * as Mongoose from 'mongoose';

export const StatsSchema = new Mongoose.Schema({
  rank: Number,
  percentile: Number,
  displayName: String,
  displayCategory: String,
  category: String,
  description: String,
  value: Number,
  displayValue: String,
  displayType: String,
});

export const CharacterStatsSchema = new Mongoose.Schema({
  dateStart: Date,
  dateEnd: Date,
  userId: String,

  platformInfo: {
    platformSlug: String,
    platformUserId: String,
    platformUserHandle: String,
    platformUserIdentifier: String,
    avatarUrl: String,
  },
  userInfo: {
    userId: Number,
  },
  stats: {
    timePlayed: StatsSchema,
    killsPvP: StatsSchema,
    killsNpc: StatsSchema,
    killsSkill: StatsSchema,
    headshots: StatsSchema,
    itemsLooted: StatsSchema,
    xPTotal: StatsSchema,
    xPClan: StatsSchema,
    specialization: StatsSchema,
    killsSpecializationSharpshooter: StatsSchema,
    killsSpecializationSurvivalist: StatsSchema,
    killsSpecializationDemolitionist: StatsSchema,
    eCreditBalance: StatsSchema,
    commendationCount: StatsSchema,
    commendationScore: StatsSchema,
    latestGearScore: StatsSchema,
    highestPlayerLevel: StatsSchema,
    xPPve: StatsSchema,
    timePlayedPve: StatsSchema,
    killsRoleElite: StatsSchema,
    killsRoleNamed: StatsSchema,
    killsFactionBlackbloc: StatsSchema,
    killsFactionCultists: StatsSchema,
    killsFactionMilitia: StatsSchema,
    killsFactionEndgame: StatsSchema,
    rankDZ: StatsSchema,
    xPDZ: StatsSchema,
    timePlayedDarkZone: StatsSchema,
    roguesKilled: StatsSchema,
    timePlayedRogue: StatsSchema,
    timePlayedRogueLongest: StatsSchema,
    killsFactionDzBlackbloc: StatsSchema,
    killsFactionDzCultists: StatsSchema,
    killsFactionDzMilitia: StatsSchema,
    killsFactionDzEndgame: StatsSchema,
    killsRoleDzElite: StatsSchema,
    killsRoleDzNamed: StatsSchema,
    latestConflictRank: StatsSchema,
    xPPvp: StatsSchema,
    timePlayedConflict: StatsSchema,
    killsBleeding: StatsSchema,
    killsBurning: StatsSchema,
    killsShocked: StatsSchema,
    killsEnsnare: StatsSchema,
    killsHeadshot: StatsSchema,
    killsWeaponShotgun: StatsSchema,
    killsWeaponSubMachinegun: StatsSchema,
    killsWeaponMounted: StatsSchema,
    killsWeaponPistol: StatsSchema,
    killsWeaponRifle: StatsSchema,
    killsWeaponGrenade: StatsSchema,
    itemsLootedPerMin: StatsSchema,
    killsPvPPerMin: StatsSchema,
    killsNpcPerMin: StatsSchema,
    playersKilled: StatsSchema,
    killsSkillPerMin: StatsSchema,
  },
});
