import { CharacterStats, Stat } from '@division-loader/apis';
import { HttpService } from '@nestjs/axios';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { AxiosError } from 'axios';
import { catchError } from 'rxjs';

@Injectable()
export class ApitrackerService {
  private readonly logger = new Logger(ApitrackerService.name);

  constructor(private readonly _httpService: HttpService, private readonly _configService: ConfigService) {}

  async getStats(player: string): Promise<CharacterStats> {
    return new Promise((resolve) => {
      this.logger.debug(`getStats(${player})`);

      if (this._configService.get<boolean>('USE_APITRACKER_MOCK', false)) {
        this.logger.warn('Use of APItracker mock !!');
        if (MOCKS[player]) {
          return resolve(this.translateAPIToStats(MOCKS[player]));
        } else {
          throw 'Not found';
        }
      }

      const URL = `https://public-api.tracker.gg/v2/division-2/standard/profile/psn/${player}`;

      this._httpService
        .get<APITrackerObj>(URL, { headers: { 'TRN-Api-Key': this._configService.get('TRN_API_KEY') } })
        .pipe(
          catchError((error: AxiosError) => {
            this.logger.error(error?.response?.data);
            throw 'Cannot load stats from apitracker !';
          })
        )
        .subscribe((response) => {
          const data = response.data;

          if (!data) {
            this.logger.error(`APItracker answer: ${response.status} ${response.statusText}`);
            throw 'Cannot load stats from apitracker !';
          }
          // this.logger.debug(data);

          resolve(this.translateAPIToStats(data));
        });
    });
  }

  translateAPIToStats(data: APITrackerObj): CharacterStats {
    const result = new CharacterStats();

    // this.logger.debug(JSON.stringify(data, null, 2));

    result.dateStart = new Date();
    result.dateEnd = result.dateStart;
    result.userId = data.data.platformInfo.platformUserIdentifier;
    result.platformInfo = data.data.platformInfo;
    result.userInfo = data.data.userInfo;
    result.stats = { ...data.data.segments[0].stats, levelPlus: new Stat() };

    if (this._configService.get<boolean>('USE_RANDOM_TIME_PLAYED', false)) {
      this.logger.warn('Use of random time played !!');
      result.stats.timePlayed.value = 10000 * Math.random();
    }

    // this.logger.debug(JSON.stringify(result, null, 2));

    return result;
  }
}

class APITrackerObj {
  'data': {
    platformInfo: {
      platformSlug: string;
      platformUserId: string;
      platformUserHandle: string;
      platformUserIdentifier: string;
      avatarUrl: string;
      additionalParameters: null;
    };
    userInfo: {
      userId: number;
      isPremium: boolean;
      isVerified: boolean;
      isInfluencer: boolean;
      isPartner: boolean;
      countryCode: string;
      customAvatarUrl: string;
      customHeroUrl: string;
      customAvatarFrame: string;
      premiumDuration: string;
      socialAccounts: [];
      pageviews: string;
      isSuspicious: boolean;
    };
    metadata: unknown;
    segments: [
      {
        type: string;
        attributes: unknown;
        metadata: {
          name: string;
        };
        expiryDate: string;
        stats: {
          timePlayed: APITrackerStatObj;
          killsPvP: APITrackerStatObj;
          killsNpc: APITrackerStatObj;
          killsSkill: APITrackerStatObj;
          headshots: APITrackerStatObj;
          itemsLooted: APITrackerStatObj;
          xPTotal: APITrackerStatObj;
          xPClan: APITrackerStatObj;
          specialization: APITrackerStatObj;
          killsSpecializationSharpshooter: APITrackerStatObj;
          killsSpecializationSurvivalist: APITrackerStatObj;
          killsSpecializationDemolitionist: APITrackerStatObj;
          eCreditBalance: APITrackerStatObj;
          commendationCount: APITrackerStatObj;
          commendationScore: APITrackerStatObj;
          latestGearScore: APITrackerStatObj;
          highestPlayerLevel: APITrackerStatObj;
          xPPve: APITrackerStatObj;
          timePlayedPve: APITrackerStatObj;
          killsRoleElite: APITrackerStatObj;
          killsRoleNamed: APITrackerStatObj;
          killsFactionBlackbloc: APITrackerStatObj;
          killsFactionCultists: APITrackerStatObj;
          killsFactionMilitia: APITrackerStatObj;
          killsFactionEndgame: APITrackerStatObj;
          rankDZ: APITrackerStatObj;
          xPDZ: APITrackerStatObj;
          timePlayedDarkZone: APITrackerStatObj;
          roguesKilled: APITrackerStatObj;
          timePlayedRogue: APITrackerStatObj;
          timePlayedRogueLongest: APITrackerStatObj;
          killsFactionDzBlackbloc: APITrackerStatObj;
          killsFactionDzCultists: APITrackerStatObj;
          killsFactionDzMilitia: APITrackerStatObj;
          killsFactionDzEndgame: APITrackerStatObj;
          killsRoleDzElite: APITrackerStatObj;
          killsRoleDzNamed: APITrackerStatObj;
          latestConflictRank: APITrackerStatObj;
          xPPvp: APITrackerStatObj;
          timePlayedConflict: APITrackerStatObj;
          killsBleeding: APITrackerStatObj;
          killsBurning: APITrackerStatObj;
          killsShocked: APITrackerStatObj;
          killsEnsnare: APITrackerStatObj;
          killsHeadshot: APITrackerStatObj;
          killsWeaponShotgun: APITrackerStatObj;
          killsWeaponSubMachinegun: APITrackerStatObj;
          killsWeaponMounted: APITrackerStatObj;
          killsWeaponPistol: APITrackerStatObj;
          killsWeaponRifle: APITrackerStatObj;
          killsWeaponGrenade: APITrackerStatObj;
          itemsLootedPerMin: APITrackerStatObj;
          killsPvPPerMin: APITrackerStatObj;
          killsNpcPerMin: APITrackerStatObj;
          playersKilled: APITrackerStatObj;
          killsSkillPerMin: APITrackerStatObj;
        };
      }
    ];
    availableSegments: [];
    expiryDate: string;
  };
}
class APITrackerStatObj {
  rank: number;
  percentile: number;
  displayName: string;
  displayCategory: string;
  category: string;
  description: string;
  metadata: unknown;
  value: number | string;
  displayValue: string;
  displayType: string;
}

const MOCKS: { [user: string]: APITrackerObj } = {
  Bibullus: {
    data: {
      platformInfo: {
        platformSlug: 'psn',
        platformUserId: null,
        platformUserHandle: 'Bibullus',
        platformUserIdentifier: 'Bibullus',
        avatarUrl: 'https://ubisoft-avatars.akamaized.net/4d7723b4-aa64-4f5d-b6bd-2f8fda65acdd/default_146_146.png',
        additionalParameters: null,
      },
      userInfo: {
        userId: 411916,
        isPremium: false,
        isVerified: false,
        isInfluencer: false,
        isPartner: false,
        countryCode: 'FR',
        customAvatarUrl: null,
        customHeroUrl: null,
        customAvatarFrame: null,
        premiumDuration: null,
        socialAccounts: [],
        pageviews: null,
        isSuspicious: false,
      },
      metadata: {},
      segments: [
        {
          type: 'overview',
          attributes: {},
          metadata: {
            name: 'Lifetime',
          },
          expiryDate: '2023-04-17T08:57:00.7543805+00:00',
          stats: {
            timePlayed: {
              rank: null,
              percentile: 58,
              displayName: 'Time Played',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 450028,
              displayValue: '125h',
              displayType: 'TimeSeconds',
            },
            killsPvP: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsNpc: {
              rank: null,
              percentile: 53,
              displayName: 'NPC Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 7627,
              displayValue: '7,627',
              displayType: 'Number',
            },
            killsSkill: {
              rank: null,
              percentile: 51,
              displayName: 'Skill Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 885,
              displayValue: '885',
              displayType: 'Number',
            },
            headshots: {
              rank: null,
              percentile: 44,
              displayName: 'Headshots',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 9497,
              displayValue: '9,497',
              displayType: 'Number',
            },
            itemsLooted: {
              rank: null,
              percentile: 53,
              displayName: 'Items Looted',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2191,
              displayValue: '2,191',
              displayType: 'Number',
            },
            xPTotal: {
              rank: null,
              percentile: 44,
              displayName: 'Total XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 21055184,
              displayValue: '21,055,184',
              displayType: 'Number',
            },
            xPClan: {
              rank: null,
              percentile: null,
              displayName: 'Clan XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            specialization: {
              rank: null,
              percentile: null,
              displayName: 'Specialization',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 'Demolitionist',
              displayValue: 'Demolitionist',
              displayType: 'String',
            },
            killsSpecializationSharpshooter: {
              rank: null,
              percentile: null,
              displayName: 'Sharpshooter Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationSurvivalist: {
              rank: null,
              percentile: null,
              displayName: 'Survivalist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationDemolitionist: {
              rank: null,
              percentile: 28,
              displayName: 'Demolitionist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 1622,
              displayValue: '1,622',
              displayType: 'Number',
            },
            eCreditBalance: {
              rank: null,
              percentile: 49,
              displayName: 'E-Credit Balance',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 44782,
              displayValue: '44,782',
              displayType: 'Number',
            },
            commendationCount: {
              rank: null,
              percentile: 56,
              displayName: 'Commendations',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 63,
              displayValue: '63',
              displayType: 'Number',
            },
            commendationScore: {
              rank: null,
              percentile: 44,
              displayName: 'Curr Comm. Score',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 660,
              displayValue: '660',
              displayType: 'Number',
            },
            latestGearScore: {
              rank: null,
              percentile: 51,
              displayName: 'Gear Score',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 547,
              displayValue: '547',
              displayType: 'Number',
            },
            highestPlayerLevel: {
              rank: null,
              percentile: 72,
              displayName: 'Player Level',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 36,
              displayValue: '36',
              displayType: 'Number',
            },
            xPPve: {
              rank: null,
              percentile: 60,
              displayName: 'PvE XP',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 21053152,
              displayValue: '21,053,152',
              displayType: 'Number',
            },
            timePlayedPve: {
              rank: null,
              percentile: 59,
              displayName: 'Time Played',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 448452,
              displayValue: '124h',
              displayType: 'TimeSeconds',
            },
            killsRoleElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleNamed: {
              rank: null,
              percentile: 46,
              displayName: 'Named Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 100,
              displayValue: '100',
              displayType: 'Number',
            },
            killsFactionBlackbloc: {
              rank: null,
              percentile: 50,
              displayName: 'Hyena Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1700,
              displayValue: '1,700',
              displayType: 'Number',
            },
            killsFactionCultists: {
              rank: null,
              percentile: 44,
              displayName: 'OutCasts Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1509,
              displayValue: '1,509',
              displayType: 'Number',
            },
            killsFactionMilitia: {
              rank: null,
              percentile: 58,
              displayName: 'TrueSons Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 2490,
              displayValue: '2,490',
              displayType: 'Number',
            },
            killsFactionEndgame: {
              rank: null,
              percentile: 32,
              displayName: 'BlackTusk Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1636,
              displayValue: '1,636',
              displayType: 'Number',
            },
            rankDZ: {
              rank: null,
              percentile: 0,
              displayName: 'DZ Level',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 2,
              displayValue: '2',
              displayType: 'Number',
            },
            xPDZ: {
              rank: null,
              percentile: 2,
              displayName: 'DZ XP',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 2032,
              displayValue: '2,032',
              displayType: 'Number',
            },
            timePlayedDarkZone: {
              rank: null,
              percentile: 10,
              displayName: 'Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 1576,
              displayValue: '26m 16s',
              displayType: 'TimeSeconds',
            },
            roguesKilled: {
              rank: null,
              percentile: null,
              displayName: 'Rogues Killed',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedRogue: {
              rank: null,
              percentile: 3,
              displayName: 'Rogue Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 42,
              displayValue: '42s',
              displayType: 'TimeSeconds',
            },
            timePlayedRogueLongest: {
              rank: null,
              percentile: 2,
              displayName: 'Rogue Longest Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21s',
              displayType: 'TimeSeconds',
            },
            killsFactionDzBlackbloc: {
              rank: null,
              percentile: 1,
              displayName: 'Hyena Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 4,
              displayValue: '4',
              displayType: 'Number',
            },
            killsFactionDzCultists: {
              rank: null,
              percentile: 8,
              displayName: 'OutCasts Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 4,
              displayValue: '4',
              displayType: 'Number',
            },
            killsFactionDzMilitia: {
              rank: null,
              percentile: null,
              displayName: 'TrueSons Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzElite: {
              rank: null,
              percentile: 5,
              displayName: 'Elite Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 2,
              displayValue: '2',
              displayType: 'Number',
            },
            killsRoleDzNamed: {
              rank: null,
              percentile: null,
              displayName: 'Named Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            latestConflictRank: {
              rank: null,
              percentile: null,
              displayName: 'Conflict Rank',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPPvp: {
              rank: null,
              percentile: null,
              displayName: 'Conflict XP',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedConflict: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsBleeding: {
              rank: null,
              percentile: 41,
              displayName: 'Bleeding Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 97,
              displayValue: '97',
              displayType: 'Number',
            },
            killsBurning: {
              rank: null,
              percentile: 38,
              displayName: 'Burning Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 142,
              displayValue: '142',
              displayType: 'Number',
            },
            killsShocked: {
              rank: null,
              percentile: 37,
              displayName: 'Shocked Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 38,
              displayValue: '38',
              displayType: 'Number',
            },
            killsEnsnare: {
              rank: null,
              percentile: 0,
              displayName: 'Ensnare Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 1,
              displayValue: '1',
              displayType: 'Number',
            },
            killsHeadshot: {
              rank: null,
              percentile: 59,
              displayName: 'Headshot Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 2023,
              displayValue: '2,023',
              displayType: 'Number',
            },
            killsWeaponShotgun: {
              rank: null,
              percentile: 76,
              displayName: 'Shotgun Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 569,
              displayValue: '569',
              displayType: 'Number',
            },
            killsWeaponSubMachinegun: {
              rank: null,
              percentile: 63,
              displayName: 'SMG Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 995,
              displayValue: '995',
              displayType: 'Number',
            },
            killsWeaponMounted: {
              rank: null,
              percentile: null,
              displayName: 'Turret Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsWeaponPistol: {
              rank: null,
              percentile: 33,
              displayName: 'Pistol Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 25,
              displayValue: '25',
              displayType: 'Number',
            },
            killsWeaponRifle: {
              rank: null,
              percentile: 47,
              displayName: 'Rifle Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 63,
              displayValue: '63',
              displayType: 'Number',
            },
            killsWeaponGrenade: {
              rank: null,
              percentile: 86,
              displayName: 'Grenade Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 302,
              displayValue: '302',
              displayType: 'Number',
            },
            itemsLootedPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Items Looted/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsPvPPerMin: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsNpcPerMin: {
              rank: null,
              percentile: 15,
              displayName: 'NPC Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.02,
              displayValue: '0.02',
              displayType: 'NumberPrecision2',
            },
            playersKilled: {
              rank: null,
              percentile: null,
              displayName: 'Players Killed',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSkillPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Skill Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
          },
        },
      ],
      availableSegments: [],
      expiryDate: '2023-04-17T08:57:00.7543805+00:00',
    },
  },
  Tarrade: {
    data: {
      platformInfo: {
        platformSlug: 'psn',
        platformUserId: null,
        platformUserHandle: 'tarrade',
        platformUserIdentifier: 'tarrade',
        avatarUrl: 'https://ubisoft-avatars.akamaized.net/87b2e5df-3780-4995-9441-5ee9a9ff1756/default_146_146.png',
        additionalParameters: null,
      },
      userInfo: {
        userId: null,
        isPremium: false,
        isVerified: false,
        isInfluencer: false,
        isPartner: false,
        countryCode: null,
        customAvatarUrl: null,
        customHeroUrl: null,
        customAvatarFrame: null,
        premiumDuration: null,
        socialAccounts: [],
        pageviews: null,
        isSuspicious: false,
      },
      metadata: {},
      segments: [
        {
          type: 'overview',
          attributes: {},
          metadata: {
            name: 'Lifetime',
          },
          expiryDate: '2023-04-17T08:56:01.9008339+00:00',
          stats: {
            timePlayed: {
              rank: null,
              percentile: 61,
              displayName: 'Time Played',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 526325,
              displayValue: '146h',
              displayType: 'TimeSeconds',
            },
            killsPvP: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsNpc: {
              rank: null,
              percentile: 67,
              displayName: 'NPC Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 15524,
              displayValue: '15,524',
              displayType: 'Number',
            },
            killsSkill: {
              rank: null,
              percentile: 69,
              displayName: 'Skill Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2241,
              displayValue: '2,241',
              displayType: 'Number',
            },
            headshots: {
              rank: null,
              percentile: 63,
              displayName: 'Headshots',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 27079,
              displayValue: '27,079',
              displayType: 'Number',
            },
            itemsLooted: {
              rank: null,
              percentile: 62,
              displayName: 'Items Looted',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 3309,
              displayValue: '3,309',
              displayType: 'Number',
            },
            xPTotal: {
              rank: null,
              percentile: 58,
              displayName: 'Total XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 46302439,
              displayValue: '46,302,439',
              displayType: 'Number',
            },
            xPClan: {
              rank: null,
              percentile: null,
              displayName: 'Clan XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            specialization: {
              rank: null,
              percentile: null,
              displayName: 'Specialization',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 'Sharpshooter',
              displayValue: 'Sharpshooter',
              displayType: 'String',
            },
            killsSpecializationSharpshooter: {
              rank: null,
              percentile: 77,
              displayName: 'Sharpshooter Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 13521,
              displayValue: '13,521',
              displayType: 'Number',
            },
            killsSpecializationSurvivalist: {
              rank: null,
              percentile: null,
              displayName: 'Survivalist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationDemolitionist: {
              rank: null,
              percentile: null,
              displayName: 'Demolitionist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            eCreditBalance: {
              rank: null,
              percentile: 61,
              displayName: 'E-Credit Balance',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 109688,
              displayValue: '109,688',
              displayType: 'Number',
            },
            commendationCount: {
              rank: null,
              percentile: 56,
              displayName: 'Commendations',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 61,
              displayValue: '61',
              displayType: 'Number',
            },
            commendationScore: {
              rank: null,
              percentile: 34,
              displayName: 'Curr Comm. Score',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 495,
              displayValue: '495',
              displayType: 'Number',
            },
            latestGearScore: {
              rank: null,
              percentile: 56,
              displayName: 'Gear Score',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 909,
              displayValue: '909',
              displayType: 'Number',
            },
            highestPlayerLevel: {
              rank: null,
              percentile: 73,
              displayName: 'Player Level',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 40,
              displayValue: '40',
              displayType: 'Number',
            },
            xPPve: {
              rank: null,
              percentile: 77,
              displayName: 'PvE XP',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 46295083,
              displayValue: '46,295,083',
              displayType: 'Number',
            },
            timePlayedPve: {
              rank: null,
              percentile: 62,
              displayName: 'Time Played',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 518331,
              displayValue: '143h',
              displayType: 'TimeSeconds',
            },
            killsRoleElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleNamed: {
              rank: null,
              percentile: 64,
              displayName: 'Named Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 307,
              displayValue: '307',
              displayType: 'Number',
            },
            killsFactionBlackbloc: {
              rank: null,
              percentile: 69,
              displayName: 'Hyena Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 3829,
              displayValue: '3,829',
              displayType: 'Number',
            },
            killsFactionCultists: {
              rank: null,
              percentile: 63,
              displayName: 'OutCasts Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 3258,
              displayValue: '3,258',
              displayType: 'Number',
            },
            killsFactionMilitia: {
              rank: null,
              percentile: 68,
              displayName: 'TrueSons Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 3890,
              displayValue: '3,890',
              displayType: 'Number',
            },
            killsFactionEndgame: {
              rank: null,
              percentile: 56,
              displayName: 'BlackTusk Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 4782,
              displayValue: '4,782',
              displayType: 'Number',
            },
            rankDZ: {
              rank: null,
              percentile: 0,
              displayName: 'DZ Level',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 2,
              displayValue: '2',
              displayType: 'Number',
            },
            xPDZ: {
              rank: null,
              percentile: 2,
              displayName: 'DZ XP',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 1701,
              displayValue: '1,701',
              displayType: 'Number',
            },
            timePlayedDarkZone: {
              rank: null,
              percentile: 29,
              displayName: 'Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 5574,
              displayValue: '1h 32m',
              displayType: 'TimeSeconds',
            },
            roguesKilled: {
              rank: null,
              percentile: null,
              displayName: 'Rogues Killed',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedRogue: {
              rank: null,
              percentile: 0,
              displayName: 'Rogue Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21s',
              displayType: 'TimeSeconds',
            },
            timePlayedRogueLongest: {
              rank: null,
              percentile: 2,
              displayName: 'Rogue Longest Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21s',
              displayType: 'TimeSeconds',
            },
            killsFactionDzBlackbloc: {
              rank: null,
              percentile: 34,
              displayName: 'Hyena Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 43,
              displayValue: '43',
              displayType: 'Number',
            },
            killsFactionDzCultists: {
              rank: null,
              percentile: 32,
              displayName: 'OutCasts Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 31,
              displayValue: '31',
              displayType: 'Number',
            },
            killsFactionDzMilitia: {
              rank: null,
              percentile: 1,
              displayName: 'TrueSons Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 4,
              displayValue: '4',
              displayType: 'Number',
            },
            killsFactionDzEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzElite: {
              rank: null,
              percentile: 30,
              displayName: 'Elite Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 28,
              displayValue: '28',
              displayType: 'Number',
            },
            killsRoleDzNamed: {
              rank: null,
              percentile: null,
              displayName: 'Named Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            latestConflictRank: {
              rank: null,
              percentile: 29,
              displayName: 'Conflict Rank',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 4,
              displayValue: '4',
              displayType: 'Number',
            },
            xPPvp: {
              rank: null,
              percentile: 35,
              displayName: 'Conflict XP',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 5655,
              displayValue: '5,655',
              displayType: 'Number',
            },
            timePlayedConflict: {
              rank: null,
              percentile: 48,
              displayName: 'Time Played',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 2391,
              displayValue: '39m 51s',
              displayType: 'TimeSeconds',
            },
            killsBleeding: {
              rank: null,
              percentile: 51,
              displayName: 'Bleeding Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 167,
              displayValue: '167',
              displayType: 'Number',
            },
            killsBurning: {
              rank: null,
              percentile: 56,
              displayName: 'Burning Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 378,
              displayValue: '378',
              displayType: 'Number',
            },
            killsShocked: {
              rank: null,
              percentile: 59,
              displayName: 'Shocked Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 109,
              displayValue: '109',
              displayType: 'Number',
            },
            killsEnsnare: {
              rank: null,
              percentile: 24,
              displayName: 'Ensnare Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 6,
              displayValue: '6',
              displayType: 'Number',
            },
            killsHeadshot: {
              rank: null,
              percentile: 74,
              displayName: 'Headshot Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 4464,
              displayValue: '4,464',
              displayType: 'Number',
            },
            killsWeaponShotgun: {
              rank: null,
              percentile: 76,
              displayName: 'Shotgun Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 553,
              displayValue: '553',
              displayType: 'Number',
            },
            killsWeaponSubMachinegun: {
              rank: null,
              percentile: 73,
              displayName: 'SMG Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 1708,
              displayValue: '1,708',
              displayType: 'Number',
            },
            killsWeaponMounted: {
              rank: null,
              percentile: null,
              displayName: 'Turret Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsWeaponPistol: {
              rank: null,
              percentile: 81,
              displayName: 'Pistol Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 523,
              displayValue: '523',
              displayType: 'Number',
            },
            killsWeaponRifle: {
              rank: null,
              percentile: 59,
              displayName: 'Rifle Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 100,
              displayValue: '100',
              displayType: 'Number',
            },
            killsWeaponGrenade: {
              rank: null,
              percentile: 37,
              displayName: 'Grenade Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 39,
              displayValue: '39',
              displayType: 'Number',
            },
            itemsLootedPerMin: {
              rank: null,
              percentile: 0,
              displayName: 'Items Looted/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.01,
              displayValue: '0.01',
              displayType: 'NumberPrecision2',
            },
            killsPvPPerMin: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsNpcPerMin: {
              rank: null,
              percentile: 66,
              displayName: 'NPC Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.03,
              displayValue: '0.03',
              displayType: 'NumberPrecision2',
            },
            playersKilled: {
              rank: null,
              percentile: null,
              displayName: 'Players Killed',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSkillPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Skill Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
          },
        },
      ],
      availableSegments: [],
      expiryDate: '2023-04-17T08:56:01.9008339+00:00',
    },
  },
  'Guizmo-1999': {
    data: {
      platformInfo: {
        platformSlug: 'psn',
        platformUserId: null,
        platformUserHandle: 'Guizmo-1999',
        platformUserIdentifier: 'Guizmo-1999',
        avatarUrl: 'https://ubisoft-avatars.akamaized.net/a297c757-963b-4d70-83e0-e2fe8082ad7b/default_146_146.png',
        additionalParameters: null,
      },
      userInfo: {
        userId: null,
        isPremium: false,
        isVerified: false,
        isInfluencer: false,
        isPartner: false,
        countryCode: null,
        customAvatarUrl: null,
        customHeroUrl: null,
        customAvatarFrame: null,
        premiumDuration: null,
        socialAccounts: [],
        pageviews: null,
        isSuspicious: false,
      },
      metadata: {},
      segments: [
        {
          type: 'overview',
          attributes: {},
          metadata: {
            name: 'Lifetime',
          },
          expiryDate: '2023-04-17T08:54:02.0678284+00:00',
          stats: {
            timePlayed: {
              rank: null,
              percentile: 60,
              displayName: 'Time Played',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 485448,
              displayValue: '134h',
              displayType: 'TimeSeconds',
            },
            killsPvP: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsNpc: {
              rank: null,
              percentile: 0,
              displayName: 'NPC Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 9656,
              displayValue: '9,656',
              displayType: 'Number',
            },
            killsSkill: {
              rank: null,
              percentile: 73,
              displayName: 'Skill Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2945,
              displayValue: '2,945',
              displayType: 'Number',
            },
            headshots: {
              rank: null,
              percentile: 55,
              displayName: 'Headshots',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 17821,
              displayValue: '17,821',
              displayType: 'Number',
            },
            itemsLooted: {
              rank: null,
              percentile: 57,
              displayName: 'Items Looted',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2555,
              displayValue: '2,555',
              displayType: 'Number',
            },
            xPTotal: {
              rank: null,
              percentile: 47,
              displayName: 'Total XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 25758998,
              displayValue: '25,758,998',
              displayType: 'Number',
            },
            xPClan: {
              rank: null,
              percentile: null,
              displayName: 'Clan XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            specialization: {
              rank: null,
              percentile: null,
              displayName: 'Specialization',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 'Demolitionist',
              displayValue: 'Demolitionist',
              displayType: 'String',
            },
            killsSpecializationSharpshooter: {
              rank: null,
              percentile: null,
              displayName: 'Sharpshooter Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationSurvivalist: {
              rank: null,
              percentile: null,
              displayName: 'Survivalist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationDemolitionist: {
              rank: null,
              percentile: 48,
              displayName: 'Demolitionist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 4185,
              displayValue: '4,185',
              displayType: 'Number',
            },
            eCreditBalance: {
              rank: null,
              percentile: 61,
              displayName: 'E-Credit Balance',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 109988,
              displayValue: '109,988',
              displayType: 'Number',
            },
            commendationCount: {
              rank: null,
              percentile: 59,
              displayName: 'Commendations',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 70,
              displayValue: '70',
              displayType: 'Number',
            },
            commendationScore: {
              rank: null,
              percentile: 49,
              displayName: 'Curr Comm. Score',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 790,
              displayValue: '790',
              displayType: 'Number',
            },
            latestGearScore: {
              rank: null,
              percentile: 48,
              displayName: 'Gear Score',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 505,
              displayValue: '505',
              displayType: 'Number',
            },
            highestPlayerLevel: {
              rank: null,
              percentile: 71,
              displayName: 'Player Level',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 34,
              displayValue: '34',
              displayType: 'Number',
            },
            xPPve: {
              rank: null,
              percentile: 65,
              displayName: 'PvE XP',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 25752383,
              displayValue: '25,752,383',
              displayType: 'Number',
            },
            timePlayedPve: {
              rank: null,
              percentile: 61,
              displayName: 'Time Played',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 481503,
              displayValue: '133h',
              displayType: 'TimeSeconds',
            },
            killsRoleElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleNamed: {
              rank: null,
              percentile: 58,
              displayName: 'Named Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 206,
              displayValue: '206',
              displayType: 'Number',
            },
            killsFactionBlackbloc: {
              rank: null,
              percentile: 59,
              displayName: 'Hyena Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 2416,
              displayValue: '2,416',
              displayType: 'Number',
            },
            killsFactionCultists: {
              rank: null,
              percentile: 56,
              displayName: 'OutCasts Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 2409,
              displayValue: '2,409',
              displayType: 'Number',
            },
            killsFactionMilitia: {
              rank: null,
              percentile: 61,
              displayName: 'TrueSons Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 2867,
              displayValue: '2,867',
              displayType: 'Number',
            },
            killsFactionEndgame: {
              rank: null,
              percentile: 35,
              displayName: 'BlackTusk Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1902,
              displayValue: '1,902',
              displayType: 'Number',
            },
            rankDZ: {
              rank: null,
              percentile: 0,
              displayName: 'DZ Level',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 2,
              displayValue: '2',
              displayType: 'Number',
            },
            xPDZ: {
              rank: null,
              percentile: 3,
              displayName: 'DZ XP',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 3335,
              displayValue: '3,335',
              displayType: 'Number',
            },
            timePlayedDarkZone: {
              rank: null,
              percentile: 18,
              displayName: 'Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 2950,
              displayValue: '49m 10s',
              displayType: 'TimeSeconds',
            },
            roguesKilled: {
              rank: null,
              percentile: null,
              displayName: 'Rogues Killed',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedRogue: {
              rank: null,
              percentile: 0,
              displayName: 'Rogue Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21s',
              displayType: 'TimeSeconds',
            },
            timePlayedRogueLongest: {
              rank: null,
              percentile: 2,
              displayName: 'Rogue Longest Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21s',
              displayType: 'TimeSeconds',
            },
            killsFactionDzBlackbloc: {
              rank: null,
              percentile: 23,
              displayName: 'Hyena Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 26,
              displayValue: '26',
              displayType: 'Number',
            },
            killsFactionDzCultists: {
              rank: null,
              percentile: 11,
              displayName: 'OutCasts Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 6,
              displayValue: '6',
              displayType: 'Number',
            },
            killsFactionDzMilitia: {
              rank: null,
              percentile: null,
              displayName: 'TrueSons Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzElite: {
              rank: null,
              percentile: 20,
              displayName: 'Elite Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 13,
              displayValue: '13',
              displayType: 'Number',
            },
            killsRoleDzNamed: {
              rank: null,
              percentile: null,
              displayName: 'Named Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            latestConflictRank: {
              rank: null,
              percentile: 18,
              displayName: 'Conflict Rank',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 3,
              displayValue: '3',
              displayType: 'Number',
            },
            xPPvp: {
              rank: null,
              percentile: 26,
              displayName: 'Conflict XP',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 3280,
              displayValue: '3,280',
              displayType: 'Number',
            },
            timePlayedConflict: {
              rank: null,
              percentile: 25,
              displayName: 'Time Played',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 697,
              displayValue: '11m 37s',
              displayType: 'TimeSeconds',
            },
            killsBleeding: {
              rank: null,
              percentile: 41,
              displayName: 'Bleeding Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 95,
              displayValue: '95',
              displayType: 'Number',
            },
            killsBurning: {
              rank: null,
              percentile: 49,
              displayName: 'Burning Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 258,
              displayValue: '258',
              displayType: 'Number',
            },
            killsShocked: {
              rank: null,
              percentile: 37,
              displayName: 'Shocked Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 39,
              displayValue: '39',
              displayType: 'Number',
            },
            killsEnsnare: {
              rank: null,
              percentile: 0,
              displayName: 'Ensnare Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 1,
              displayValue: '1',
              displayType: 'Number',
            },
            killsHeadshot: {
              rank: null,
              percentile: 54,
              displayName: 'Headshot Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 1552,
              displayValue: '1,552',
              displayType: 'Number',
            },
            killsWeaponShotgun: {
              rank: null,
              percentile: 80,
              displayName: 'Shotgun Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 732,
              displayValue: '732',
              displayType: 'Number',
            },
            killsWeaponSubMachinegun: {
              rank: null,
              percentile: 60,
              displayName: 'SMG Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 857,
              displayValue: '857',
              displayType: 'Number',
            },
            killsWeaponMounted: {
              rank: null,
              percentile: null,
              displayName: 'Turret Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsWeaponPistol: {
              rank: null,
              percentile: 14,
              displayName: 'Pistol Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 7,
              displayValue: '7',
              displayType: 'Number',
            },
            killsWeaponRifle: {
              rank: null,
              percentile: 55,
              displayName: 'Rifle Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 88,
              displayValue: '88',
              displayType: 'Number',
            },
            killsWeaponGrenade: {
              rank: null,
              percentile: 48,
              displayName: 'Grenade Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 64,
              displayValue: '64',
              displayType: 'Number',
            },
            itemsLootedPerMin: {
              rank: null,
              percentile: 0,
              displayName: 'Items Looted/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.01,
              displayValue: '0.01',
              displayType: 'NumberPrecision2',
            },
            killsPvPPerMin: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsNpcPerMin: {
              rank: null,
              percentile: 15,
              displayName: 'NPC Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.02,
              displayValue: '0.02',
              displayType: 'NumberPrecision2',
            },
            playersKilled: {
              rank: null,
              percentile: null,
              displayName: 'Players Killed',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSkillPerMin: {
              rank: null,
              percentile: 0,
              displayName: 'Skill Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.01,
              displayValue: '0.01',
              displayType: 'NumberPrecision2',
            },
          },
        },
      ],
      availableSegments: [],
      expiryDate: '2023-04-17T08:54:02.0678284+00:00',
    },
  },
};
