import { CharacterStats } from '@division-loader/apis';
import { HttpService } from '@nestjs/axios';
import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { AxiosError } from 'axios';
import { catchError } from 'rxjs';

@Injectable()
export class ApitrackerService {
  private readonly logger = new Logger(ApitrackerService.name);

  constructor(private readonly _httpService: HttpService, private readonly _configService: ConfigService) {}

  async getStats(player: string): Promise<CharacterStats> {
    return new Promise((resolve) => {
      this.logger.debug(`getStats(${player})`);

      if (this._configService.get<boolean>('USE_APITRACKER_MOCK', false)) {
        this.logger.warn('Use of APItracker mock !!');
        if (MOCKS[player]) {
          return resolve(this.translateAPIToStats(MOCKS[player]));
        } else {
          throw 'Not found';
        }
      }

      const URL = `https://public-api.tracker.gg/v2/division-2/standard/profile/psn/${player}`;

      this._httpService
        .get<APITrackerObj>(URL, { headers: { 'TRN-Api-Key': this._configService.get('TRN_API_KEY') } })
        .pipe(
          catchError((error: AxiosError) => {
            this.logger.error(error?.response?.data);
            throw 'Cannot load stats from apitracker !';
          })
        )
        .subscribe((response) => {
          const data = response.data;

          if (!data) {
            this.logger.error(`APItracker answer: ${response.status} ${response.statusText}`);
            throw 'Cannot load stats from apitracker !';
          }
          // this.logger.debug(data);

          resolve(this.translateAPIToStats(data));
        });
    });
  }

  translateAPIToStats(data: APITrackerObj): CharacterStats {
    const result = new CharacterStats();

    // this.logger.debug(JSON.stringify(data, null, 2));

    result.dateStart = new Date();
    result.dateEnd = result.dateStart;
    result.userId = data.data.platformInfo.platformUserIdentifier;
    result.platformInfo = data.data.platformInfo;
    result.userInfo = data.data.userInfo;
    result.stats = data.data.segments[0].stats;

    if (this._configService.get<boolean>('USE_RANDOM_TIME_PLAYED', false)) {
      this.logger.warn('Use of random time played !!');
      result.stats.timePlayed.value = 10000 * Math.random();
    }

    // this.logger.debug(JSON.stringify(result, null, 2));

    return result;
  }
}

class APITrackerObj {
  'data': {
    platformInfo: {
      platformSlug: string;
      platformUserId: string;
      platformUserHandle: string;
      platformUserIdentifier: string;
      avatarUrl: string;
      additionalParameters: null;
    };
    userInfo: {
      userId: number;
      isPremium: boolean;
      isVerified: boolean;
      isInfluencer: boolean;
      isPartner: boolean;
      countryCode: string;
      customAvatarUrl: string;
      customHeroUrl: string;
      socialAccounts: [];
      pageviews: string;
      isSuspicious: string;
    };
    metadata: unknown;
    segments: [
      {
        type: string;
        attributes: unknown;
        metadata: {
          name: string;
        };
        expiryDate: string;
        stats: {
          timePlayed: APITrackerStatObj;
          killsPvP: APITrackerStatObj;
          killsNpc: APITrackerStatObj;
          killsSkill: APITrackerStatObj;
          headshots: APITrackerStatObj;
          itemsLooted: APITrackerStatObj;
          xPTotal: APITrackerStatObj;
          xPClan: APITrackerStatObj;
          specialization: APITrackerStatObj;
          killsSpecializationSharpshooter: APITrackerStatObj;
          killsSpecializationSurvivalist: APITrackerStatObj;
          killsSpecializationDemolitionist: APITrackerStatObj;
          eCreditBalance: APITrackerStatObj;
          commendationCount: APITrackerStatObj;
          commendationScore: APITrackerStatObj;
          latestGearScore: APITrackerStatObj;
          highestPlayerLevel: APITrackerStatObj;
          xPPve: APITrackerStatObj;
          timePlayedPve: APITrackerStatObj;
          killsRoleElite: APITrackerStatObj;
          killsRoleNamed: APITrackerStatObj;
          killsFactionBlackbloc: APITrackerStatObj;
          killsFactionCultists: APITrackerStatObj;
          killsFactionMilitia: APITrackerStatObj;
          killsFactionEndgame: APITrackerStatObj;
          rankDZ: APITrackerStatObj;
          xPDZ: APITrackerStatObj;
          timePlayedDarkZone: APITrackerStatObj;
          roguesKilled: APITrackerStatObj;
          timePlayedRogue: APITrackerStatObj;
          timePlayedRogueLongest: APITrackerStatObj;
          killsFactionDzBlackbloc: APITrackerStatObj;
          killsFactionDzCultists: APITrackerStatObj;
          killsFactionDzMilitia: APITrackerStatObj;
          killsFactionDzEndgame: APITrackerStatObj;
          killsRoleDzElite: APITrackerStatObj;
          killsRoleDzNamed: APITrackerStatObj;
          latestConflictRank: APITrackerStatObj;
          xPPvp: APITrackerStatObj;
          timePlayedConflict: APITrackerStatObj;
          killsBleeding: APITrackerStatObj;
          killsBurning: APITrackerStatObj;
          killsShocked: APITrackerStatObj;
          killsEnsnare: APITrackerStatObj;
          killsHeadshot: APITrackerStatObj;
          killsWeaponShotgun: APITrackerStatObj;
          killsWeaponSubMachinegun: APITrackerStatObj;
          killsWeaponMounted: APITrackerStatObj;
          killsWeaponPistol: APITrackerStatObj;
          killsWeaponRifle: APITrackerStatObj;
          killsWeaponGrenade: APITrackerStatObj;
          itemsLootedPerMin: APITrackerStatObj;
          killsPvPPerMin: APITrackerStatObj;
          killsNpcPerMin: APITrackerStatObj;
          playersKilled: APITrackerStatObj;
          killsSkillPerMin: APITrackerStatObj;
        };
      }
    ];
    availableSegments: [];
    expiryDate: string;
  };
}
class APITrackerStatObj {
  rank: number;
  percentile: number;
  displayName: string;
  displayCategory: string;
  category: string;
  description: string;
  metadata: unknown;
  value: number | string;
  displayValue: string;
  displayType: string;
}

const MOCKS: { [user: string]: APITrackerObj } = {
  Bibullus: {
    data: {
      platformInfo: {
        platformSlug: 'psn',
        platformUserId: '4d7723b4-aa64-4f5d-b6bd-2f8fda65acdd',
        platformUserHandle: 'Bibullus',
        platformUserIdentifier: 'Bibullus',
        avatarUrl: 'https://ubisoft-avatars.akamaized.net/4d7723b4-aa64-4f5d-b6bd-2f8fda65acdd/default_146_146.png',
        additionalParameters: null,
      },
      userInfo: {
        userId: 411916,
        isPremium: false,
        isVerified: false,
        isInfluencer: false,
        isPartner: false,
        countryCode: 'FR',
        customAvatarUrl: null,
        customHeroUrl: null,
        socialAccounts: [],
        pageviews: null,
        isSuspicious: null,
      },
      metadata: {},
      segments: [
        {
          type: 'overview',
          attributes: {},
          metadata: {
            name: 'Lifetime',
          },
          expiryDate: '2023-02-28T14:45:31.3349856+00:00',
          stats: {
            timePlayed: {
              rank: null,
              percentile: 28.0,
              displayName: 'Time Played',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 96489,
              displayValue: '26h',
              displayType: 'TimeSeconds',
            },
            killsPvP: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsNpc: {
              rank: null,
              percentile: 27.0,
              displayName: 'NPC Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 1974,
              displayValue: '1,974',
              displayType: 'Number',
            },
            killsSkill: {
              rank: null,
              percentile: 18.0,
              displayName: 'Skill Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 116,
              displayValue: '116',
              displayType: 'Number',
            },
            headshots: {
              rank: null,
              percentile: 23.0,
              displayName: 'Headshots',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2312,
              displayValue: '2,312',
              displayType: 'Number',
            },
            itemsLooted: {
              rank: null,
              percentile: 24.0,
              displayName: 'Items Looted',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 370,
              displayValue: '370',
              displayType: 'Number',
            },
            xPTotal: {
              rank: null,
              percentile: 19.0,
              displayName: 'Total XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 801853,
              displayValue: '801,853',
              displayType: 'Number',
            },
            xPClan: {
              rank: null,
              percentile: null,
              displayName: 'Clan XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            specialization: {
              rank: null,
              percentile: null,
              displayName: 'Specialization',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: null,
              displayValue: null,
              displayType: 'String',
            },
            killsSpecializationSharpshooter: {
              rank: null,
              percentile: null,
              displayName: 'Sharpshooter Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationSurvivalist: {
              rank: null,
              percentile: null,
              displayName: 'Survivalist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationDemolitionist: {
              rank: null,
              percentile: null,
              displayName: 'Demolitionist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            eCreditBalance: {
              rank: null,
              percentile: 21.0,
              displayName: 'E-Credit Balance',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 1372,
              displayValue: '1,372',
              displayType: 'Number',
            },
            commendationCount: {
              rank: null,
              percentile: 30.0,
              displayName: 'Commendations',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21',
              displayType: 'Number',
            },
            commendationScore: {
              rank: null,
              percentile: 9.0,
              displayName: 'Curr Comm. Score',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 160,
              displayValue: '160',
              displayType: 'Number',
            },
            latestGearScore: {
              rank: null,
              percentile: null,
              displayName: 'Gear Score',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            highestPlayerLevel: {
              rank: null,
              percentile: 28.0,
              displayName: 'Player Level',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 17,
              displayValue: '17',
              displayType: 'Number',
            },
            xPPve: {
              rank: null,
              percentile: 21.0,
              displayName: 'PvE XP',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 801853,
              displayValue: '801,853',
              displayType: 'Number',
            },
            timePlayedPve: {
              rank: null,
              percentile: 28.0,
              displayName: 'Time Played',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 96220,
              displayValue: '26h',
              displayType: 'TimeSeconds',
            },
            killsRoleElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleNamed: {
              rank: null,
              percentile: 17.0,
              displayName: 'Named Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 10,
              displayValue: '10',
              displayType: 'Number',
            },
            killsFactionBlackbloc: {
              rank: null,
              percentile: 26.0,
              displayName: 'Hyena Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 705,
              displayValue: '705',
              displayType: 'Number',
            },
            killsFactionCultists: {
              rank: null,
              percentile: 5.0,
              displayName: 'OutCasts Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 14,
              displayValue: '14',
              displayType: 'Number',
            },
            killsFactionMilitia: {
              rank: null,
              percentile: 36.0,
              displayName: 'TrueSons Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1139,
              displayValue: '1,139',
              displayType: 'Number',
            },
            killsFactionEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            rankDZ: {
              rank: null,
              percentile: null,
              displayName: 'DZ Level',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPDZ: {
              rank: null,
              percentile: null,
              displayName: 'DZ XP',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedDarkZone: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            roguesKilled: {
              rank: null,
              percentile: null,
              displayName: 'Rogues Killed',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedRogue: {
              rank: null,
              percentile: null,
              displayName: 'Rogue Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            timePlayedRogueLongest: {
              rank: null,
              percentile: null,
              displayName: 'Rogue Longest Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsFactionDzBlackbloc: {
              rank: null,
              percentile: null,
              displayName: 'Hyena Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzCultists: {
              rank: null,
              percentile: null,
              displayName: 'OutCasts Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzMilitia: {
              rank: null,
              percentile: null,
              displayName: 'TrueSons Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzNamed: {
              rank: null,
              percentile: null,
              displayName: 'Named Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            latestConflictRank: {
              rank: null,
              percentile: null,
              displayName: 'Conflict Rank',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPPvp: {
              rank: null,
              percentile: null,
              displayName: 'Conflict XP',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedConflict: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsBleeding: {
              rank: null,
              percentile: 13.0,
              displayName: 'Bleeding Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 10,
              displayValue: '10',
              displayType: 'Number',
            },
            killsBurning: {
              rank: null,
              percentile: 15.0,
              displayName: 'Burning Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 15,
              displayValue: '15',
              displayType: 'Number',
            },
            killsShocked: {
              rank: null,
              percentile: 16.0,
              displayName: 'Shocked Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 10,
              displayValue: '10',
              displayType: 'Number',
            },
            killsEnsnare: {
              rank: null,
              percentile: null,
              displayName: 'Ensnare Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsHeadshot: {
              rank: null,
              percentile: 28.0,
              displayName: 'Headshot Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 397,
              displayValue: '397',
              displayType: 'Number',
            },
            killsWeaponShotgun: {
              rank: null,
              percentile: 74.0,
              displayName: 'Shotgun Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 469,
              displayValue: '469',
              displayType: 'Number',
            },
            killsWeaponSubMachinegun: {
              rank: null,
              percentile: 41.0,
              displayName: 'SMG Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 318,
              displayValue: '318',
              displayType: 'Number',
            },
            killsWeaponMounted: {
              rank: null,
              percentile: null,
              displayName: 'Turret Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsWeaponPistol: {
              rank: null,
              percentile: 19.0,
              displayName: 'Pistol Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 10,
              displayValue: '10',
              displayType: 'Number',
            },
            killsWeaponRifle: {
              rank: null,
              percentile: 13.0,
              displayName: 'Rifle Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 9,
              displayValue: '9',
              displayType: 'Number',
            },
            killsWeaponGrenade: {
              rank: null,
              percentile: 52.0,
              displayName: 'Grenade Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 74,
              displayValue: '74',
              displayType: 'Number',
            },
            itemsLootedPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Items Looted/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsPvPPerMin: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsNpcPerMin: {
              rank: null,
              percentile: 15.0,
              displayName: 'NPC Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.02,
              displayValue: '0.02',
              displayType: 'NumberPrecision2',
            },
            playersKilled: {
              rank: null,
              percentile: null,
              displayName: 'Players Killed',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSkillPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Skill Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
          },
        },
      ],
      availableSegments: [],
      expiryDate: '2023-02-28T14:45:31.3349856+00:00',
    },
  },
  Tarrade: {
    data: {
      platformInfo: {
        platformSlug: 'psn',
        platformUserId: '87b2e5df-3780-4995-9441-5ee9a9ff1756',
        platformUserHandle: 'tarrade',
        platformUserIdentifier: 'tarrade',
        avatarUrl: 'https://ubisoft-avatars.akamaized.net/87b2e5df-3780-4995-9441-5ee9a9ff1756/default_146_146.png',
        additionalParameters: null,
      },
      userInfo: {
        userId: null,
        isPremium: false,
        isVerified: false,
        isInfluencer: false,
        isPartner: false,
        countryCode: null,
        customAvatarUrl: null,
        customHeroUrl: null,
        socialAccounts: [],
        pageviews: null,
        isSuspicious: null,
      },
      metadata: {},
      segments: [
        {
          type: 'overview',
          attributes: {},
          metadata: {
            name: 'Lifetime',
          },
          expiryDate: '2023-02-28T17:59:00.3911379+00:00',
          stats: {
            timePlayed: {
              rank: null,
              percentile: 30,
              displayName: 'Time Played',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 111926,
              displayValue: '31h',
              displayType: 'TimeSeconds',
            },
            killsPvP: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsNpc: {
              rank: null,
              percentile: 32,
              displayName: 'NPC Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2713,
              displayValue: '2,713',
              displayType: 'Number',
            },
            killsSkill: {
              rank: null,
              percentile: 23,
              displayName: 'Skill Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 179,
              displayValue: '179',
              displayType: 'Number',
            },
            headshots: {
              rank: null,
              percentile: 26,
              displayName: 'Headshots',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2907,
              displayValue: '2,907',
              displayType: 'Number',
            },
            itemsLooted: {
              rank: null,
              percentile: 27,
              displayName: 'Items Looted',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 509,
              displayValue: '509',
              displayType: 'Number',
            },
            xPTotal: {
              rank: null,
              percentile: 23,
              displayName: 'Total XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 2190994,
              displayValue: '2,190,994',
              displayType: 'Number',
            },
            xPClan: {
              rank: null,
              percentile: null,
              displayName: 'Clan XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            specialization: {
              rank: null,
              percentile: null,
              displayName: 'Specialization',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 'Sharpshooter',
              displayValue: null,
              displayType: 'String',
            },
            killsSpecializationSharpshooter: {
              rank: null,
              percentile: null,
              displayName: 'Sharpshooter Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationSurvivalist: {
              rank: null,
              percentile: null,
              displayName: 'Survivalist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationDemolitionist: {
              rank: null,
              percentile: null,
              displayName: 'Demolitionist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            eCreditBalance: {
              rank: null,
              percentile: 30,
              displayName: 'E-Credit Balance',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 7001,
              displayValue: '7,001',
              displayType: 'Number',
            },
            commendationCount: {
              rank: null,
              percentile: 23,
              displayName: 'Commendations',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 15,
              displayValue: '15',
              displayType: 'Number',
            },
            commendationScore: {
              rank: null,
              percentile: 10,
              displayName: 'Curr Comm. Score',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 180,
              displayValue: '180',
              displayType: 'Number',
            },
            latestGearScore: {
              rank: null,
              percentile: 1,
              displayName: 'Gear Score',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 23,
              displayValue: '23',
              displayType: 'Number',
            },
            highestPlayerLevel: {
              rank: null,
              percentile: 34,
              displayName: 'Player Level',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 24,
              displayValue: '24',
              displayType: 'Number',
            },
            xPPve: {
              rank: null,
              percentile: 26,
              displayName: 'PvE XP',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 2190994,
              displayValue: '2,190,994',
              displayType: 'Number',
            },
            timePlayedPve: {
              rank: null,
              percentile: 30,
              displayName: 'Time Played',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 111926,
              displayValue: '31h',
              displayType: 'TimeSeconds',
            },
            killsRoleElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleNamed: {
              rank: null,
              percentile: 24,
              displayName: 'Named Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21',
              displayType: 'Number',
            },
            killsFactionBlackbloc: {
              rank: null,
              percentile: 41,
              displayName: 'Hyena Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1224,
              displayValue: '1,224',
              displayType: 'Number',
            },
            killsFactionCultists: {
              rank: null,
              percentile: 11,
              displayName: 'OutCasts Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 142,
              displayValue: '142',
              displayType: 'Number',
            },
            killsFactionMilitia: {
              rank: null,
              percentile: 41,
              displayName: 'TrueSons Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1345,
              displayValue: '1,345',
              displayType: 'Number',
            },
            killsFactionEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            rankDZ: {
              rank: null,
              percentile: null,
              displayName: 'DZ Level',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPDZ: {
              rank: null,
              percentile: null,
              displayName: 'DZ XP',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedDarkZone: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            roguesKilled: {
              rank: null,
              percentile: null,
              displayName: 'Rogues Killed',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedRogue: {
              rank: null,
              percentile: null,
              displayName: 'Rogue Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            timePlayedRogueLongest: {
              rank: null,
              percentile: null,
              displayName: 'Rogue Longest Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsFactionDzBlackbloc: {
              rank: null,
              percentile: null,
              displayName: 'Hyena Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzCultists: {
              rank: null,
              percentile: null,
              displayName: 'OutCasts Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzMilitia: {
              rank: null,
              percentile: null,
              displayName: 'TrueSons Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzNamed: {
              rank: null,
              percentile: null,
              displayName: 'Named Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            latestConflictRank: {
              rank: null,
              percentile: null,
              displayName: 'Conflict Rank',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPPvp: {
              rank: null,
              percentile: null,
              displayName: 'Conflict XP',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedConflict: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsBleeding: {
              rank: null,
              percentile: 16,
              displayName: 'Bleeding Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 14,
              displayValue: '14',
              displayType: 'Number',
            },
            killsBurning: {
              rank: null,
              percentile: 23,
              displayName: 'Burning Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 41,
              displayValue: '41',
              displayType: 'Number',
            },
            killsShocked: {
              rank: null,
              percentile: 11,
              displayName: 'Shocked Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 6,
              displayValue: '6',
              displayType: 'Number',
            },
            killsEnsnare: {
              rank: null,
              percentile: null,
              displayName: 'Ensnare Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsHeadshot: {
              rank: null,
              percentile: 40,
              displayName: 'Headshot Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 805,
              displayValue: '805',
              displayType: 'Number',
            },
            killsWeaponShotgun: {
              rank: null,
              percentile: 37,
              displayName: 'Shotgun Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 73,
              displayValue: '73',
              displayType: 'Number',
            },
            killsWeaponSubMachinegun: {
              rank: null,
              percentile: 31,
              displayName: 'SMG Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 182,
              displayValue: '182',
              displayType: 'Number',
            },
            killsWeaponMounted: {
              rank: null,
              percentile: null,
              displayName: 'Turret Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsWeaponPistol: {
              rank: null,
              percentile: 30,
              displayName: 'Pistol Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 21,
              displayValue: '21',
              displayType: 'Number',
            },
            killsWeaponRifle: {
              rank: null,
              percentile: 40,
              displayName: 'Rifle Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 44,
              displayValue: '44',
              displayType: 'Number',
            },
            killsWeaponGrenade: {
              rank: null,
              percentile: 8,
              displayName: 'Grenade Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 5,
              displayValue: '5',
              displayType: 'Number',
            },
            itemsLootedPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Items Looted/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsPvPPerMin: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsNpcPerMin: {
              rank: null,
              percentile: 15,
              displayName: 'NPC Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.02,
              displayValue: '0.02',
              displayType: 'NumberPrecision2',
            },
            playersKilled: {
              rank: null,
              percentile: null,
              displayName: 'Players Killed',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSkillPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Skill Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
          },
        },
      ],
      availableSegments: [],
      expiryDate: '2023-02-28T17:59:00.3911379+00:00',
    },
  },
  'Guizmo-1999': {
    data: {
      platformInfo: {
        platformSlug: 'psn',
        platformUserId: 'a297c757-963b-4d70-83e0-e2fe8082ad7b',
        platformUserHandle: 'Guizmo-1999',
        platformUserIdentifier: 'Guizmo-1999',
        avatarUrl: 'https://ubisoft-avatars.akamaized.net/a297c757-963b-4d70-83e0-e2fe8082ad7b/default_146_146.png',
        additionalParameters: null,
      },
      userInfo: {
        userId: null,
        isPremium: false,
        isVerified: false,
        isInfluencer: false,
        isPartner: false,
        countryCode: null,
        customAvatarUrl: null,
        customHeroUrl: null,
        socialAccounts: [],
        pageviews: null,
        isSuspicious: null,
      },
      metadata: {},
      segments: [
        {
          type: 'overview',
          attributes: {},
          metadata: {
            name: 'Lifetime',
          },
          expiryDate: '2023-02-28T18:01:00.4468531+00:00',
          stats: {
            timePlayed: {
              rank: null,
              percentile: 40,
              displayName: 'Time Played',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 190440,
              displayValue: '52h',
              displayType: 'TimeSeconds',
            },
            killsPvP: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsNpc: {
              rank: null,
              percentile: 35,
              displayName: 'NPC Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 3374,
              displayValue: '3,374',
              displayType: 'Number',
            },
            killsSkill: {
              rank: null,
              percentile: 45,
              displayName: 'Skill Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 656,
              displayValue: '656',
              displayType: 'Number',
            },
            headshots: {
              rank: null,
              percentile: 31,
              displayName: 'Headshots',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 4256,
              displayValue: '4,256',
              displayType: 'Number',
            },
            itemsLooted: {
              rank: null,
              percentile: 33,
              displayName: 'Items Looted',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 752,
              displayValue: '752',
              displayType: 'Number',
            },
            xPTotal: {
              rank: null,
              percentile: 26,
              displayName: 'Total XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 3831938,
              displayValue: '3,831,938',
              displayType: 'Number',
            },
            xPClan: {
              rank: null,
              percentile: null,
              displayName: 'Clan XP',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            specialization: {
              rank: null,
              percentile: null,
              displayName: 'Specialization',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: null,
              displayValue: null,
              displayType: 'String',
            },
            killsSpecializationSharpshooter: {
              rank: null,
              percentile: null,
              displayName: 'Sharpshooter Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationSurvivalist: {
              rank: null,
              percentile: null,
              displayName: 'Survivalist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSpecializationDemolitionist: {
              rank: null,
              percentile: null,
              displayName: 'Demolitionist Kills',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            eCreditBalance: {
              rank: null,
              percentile: 32,
              displayName: 'E-Credit Balance',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 9016,
              displayValue: '9,016',
              displayType: 'Number',
            },
            commendationCount: {
              rank: null,
              percentile: 36,
              displayName: 'Commendations',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 27,
              displayValue: '27',
              displayType: 'Number',
            },
            commendationScore: {
              rank: null,
              percentile: 13,
              displayName: 'Curr Comm. Score',
              displayCategory: 'General',
              category: 'general',
              description: null,
              metadata: {},
              value: 215,
              displayValue: '215',
              displayType: 'Number',
            },
            latestGearScore: {
              rank: null,
              percentile: 6,
              displayName: 'Gear Score',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 215,
              displayValue: '215',
              displayType: 'Number',
            },
            highestPlayerLevel: {
              rank: null,
              percentile: 37,
              displayName: 'Player Level',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 29,
              displayValue: '29',
              displayType: 'Number',
            },
            xPPve: {
              rank: null,
              percentile: 28,
              displayName: 'PvE XP',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 3831938,
              displayValue: '3,831,938',
              displayType: 'Number',
            },
            timePlayedPve: {
              rank: null,
              percentile: 41,
              displayName: 'Time Played',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 190146,
              displayValue: '52h',
              displayType: 'TimeSeconds',
            },
            killsRoleElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleNamed: {
              rank: null,
              percentile: 30,
              displayName: 'Named Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 37,
              displayValue: '37',
              displayType: 'Number',
            },
            killsFactionBlackbloc: {
              rank: null,
              percentile: 44,
              displayName: 'Hyena Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1396,
              displayValue: '1,396',
              displayType: 'Number',
            },
            killsFactionCultists: {
              rank: null,
              percentile: 20,
              displayName: 'OutCasts Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 502,
              displayValue: '502',
              displayType: 'Number',
            },
            killsFactionMilitia: {
              rank: null,
              percentile: 42,
              displayName: 'TrueSons Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 1377,
              displayValue: '1,377',
              displayType: 'Number',
            },
            killsFactionEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'PvE',
              category: 'pve',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            rankDZ: {
              rank: null,
              percentile: null,
              displayName: 'DZ Level',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPDZ: {
              rank: null,
              percentile: null,
              displayName: 'DZ XP',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedDarkZone: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            roguesKilled: {
              rank: null,
              percentile: null,
              displayName: 'Rogues Killed',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedRogue: {
              rank: null,
              percentile: null,
              displayName: 'Rogue Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            timePlayedRogueLongest: {
              rank: null,
              percentile: null,
              displayName: 'Rogue Longest Time Played',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsFactionDzBlackbloc: {
              rank: null,
              percentile: null,
              displayName: 'Hyena Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzCultists: {
              rank: null,
              percentile: null,
              displayName: 'OutCasts Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzMilitia: {
              rank: null,
              percentile: null,
              displayName: 'TrueSons Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsFactionDzEndgame: {
              rank: null,
              percentile: null,
              displayName: 'BlackTusk Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzElite: {
              rank: null,
              percentile: null,
              displayName: 'Elite Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsRoleDzNamed: {
              rank: null,
              percentile: null,
              displayName: 'Named Kills',
              displayCategory: 'Dark Zone',
              category: 'darkZone',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            latestConflictRank: {
              rank: null,
              percentile: null,
              displayName: 'Conflict Rank',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            xPPvp: {
              rank: null,
              percentile: null,
              displayName: 'Conflict XP',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            timePlayedConflict: {
              rank: null,
              percentile: null,
              displayName: 'Time Played',
              displayCategory: 'Conflict PvP',
              category: 'conflictPvp',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0s',
              displayType: 'TimeSeconds',
            },
            killsBleeding: {
              rank: null,
              percentile: 17,
              displayName: 'Bleeding Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 16,
              displayValue: '16',
              displayType: 'Number',
            },
            killsBurning: {
              rank: null,
              percentile: 23,
              displayName: 'Burning Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 41,
              displayValue: '41',
              displayType: 'Number',
            },
            killsShocked: {
              rank: null,
              percentile: 21,
              displayName: 'Shocked Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 15,
              displayValue: '15',
              displayType: 'Number',
            },
            killsEnsnare: {
              rank: null,
              percentile: null,
              displayName: 'Ensnare Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsHeadshot: {
              rank: null,
              percentile: 35,
              displayName: 'Headshot Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 643,
              displayValue: '643',
              displayType: 'Number',
            },
            killsWeaponShotgun: {
              rank: null,
              percentile: 36,
              displayName: 'Shotgun Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 69,
              displayValue: '69',
              displayType: 'Number',
            },
            killsWeaponSubMachinegun: {
              rank: null,
              percentile: 41,
              displayName: 'SMG Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 330,
              displayValue: '330',
              displayType: 'Number',
            },
            killsWeaponMounted: {
              rank: null,
              percentile: null,
              displayName: 'Turret Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsWeaponPistol: {
              rank: null,
              percentile: 8,
              displayName: 'Pistol Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 4,
              displayValue: '4',
              displayType: 'Number',
            },
            killsWeaponRifle: {
              rank: null,
              percentile: 44,
              displayName: 'Rifle Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 53,
              displayValue: '53',
              displayType: 'Number',
            },
            killsWeaponGrenade: {
              rank: null,
              percentile: 28,
              displayName: 'Grenade Kills',
              displayCategory: 'Kills',
              category: 'kills',
              description: null,
              metadata: {},
              value: 25,
              displayValue: '25',
              displayType: 'Number',
            },
            itemsLootedPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Items Looted/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsPvPPerMin: {
              rank: null,
              percentile: null,
              displayName: 'PvP Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
            killsNpcPerMin: {
              rank: null,
              percentile: 15,
              displayName: 'NPC Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0.02,
              displayValue: '0.02',
              displayType: 'NumberPrecision2',
            },
            playersKilled: {
              rank: null,
              percentile: null,
              displayName: 'Players Killed',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0',
              displayType: 'Number',
            },
            killsSkillPerMin: {
              rank: null,
              percentile: null,
              displayName: 'Skill Kills/Min',
              displayCategory: '',
              category: null,
              description: null,
              metadata: {},
              value: 0,
              displayValue: '0.00',
              displayType: 'NumberPrecision2',
            },
          },
        },
      ],
      availableSegments: [],
      expiryDate: '2023-02-28T18:01:00.4468531+00:00',
    },
  },
};
